# Generated by Django 5.2 on 2025-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_tuning', '0002_comingsoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='cars/3d_models/', verbose_name='3D модель'),
        ),
    ]
